name: BussieShift
services:
  BussieShift:
    image: docker.io/library/hermes_pdf_shift_http
    ports:
      - 8080:8080
    volumes:
      - ./Dienstboek:/usr/src/hermes_pdf_shift_http/Dienstboek/
    restart: on-failure